version: '3.8'
services:
  jenkins:
    image: custom-jenkins-predeploy
    container_name: codep_jenkins
    user: root
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs
      - JENKINS_OPTS=--httpPort=8080
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - codep_jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - codep_network
    depends_on:
      - docker
    restart: unless-stopped
  docker:
    image: docker:24.0.7-dind
    container_name: codep_docker
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - codep_jenkins_docker_certs:/certs/client
      - codep_jenkins_data:/var/jenkins_home
    networks:
      - codep_network
    restart: unless-stopped
  nexus:
    image: sonatype/nexus3:3.80.0
    container_name: codep_nexus
    ports:
      - "8081:8081"
    volumes:
      - codep_nexus_data:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms1200m -Xmx1200m -XX:MaxDirectMemorySize=2g
    networks:
      - codep_network
    restart: unless-stopped
  gitlab:
    image: gitlab/gitlab-ee:16.6.2-ee.0
    container_name: codep_gitlab
    hostname: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:11180'
        nginx['listen_port'] = 80
        gitlab_rails['gitlab_shell_ssh_port'] = 10022
        postgresql['enable'] = false
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_host'] = 'gitlab-db'
        gitlab_rails['db_port'] = 5432
        gitlab_rails['db_username'] = 'gitlab'
        gitlab_rails['db_password'] = 'gitlab_password'
        gitlab_rails['db_database'] = 'gitlabhq_production'
        redis['enable'] = false
        gitlab_rails['redis_host'] = 'redis'
        gitlab_rails['redis_port'] = 6379
    ports:
      - "11180:80"
      - "10022:22"
    volumes:
      - codep_gitlab_config:/etc/gitlab
      - codep_gitlab_logs:/var/log/gitlab
      - codep_gitlab_data:/var/opt/gitlab
    networks:
      - codep_network
    depends_on:
      gitlab-db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped
  gitlab-db:
    image: postgres:16.1
    container_name: codep_gitlab_db
    environment:
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: gitlab_password
      POSTGRES_DB: gitlabhq_production
    volumes:
      - codep_gitlab_postgres:/var/lib/postgresql/data
    networks:
      - codep_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gitlab"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  redis:
    image: redis:7.0.12
    container_name: codep_redis
    volumes:
      - codep_redis_data:/data
    networks:
      - codep_network
    restart: unless-stopped
  sonarqube:
    image: sonarqube:10.3.0-community
    container_name: codep_sonarqube
    depends_on:
      - sonarqube-db
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
      - SONAR_SEARCH_JAVAADDITIONALOPTS=-Dnode.store.allow_mmap=false
    ports:
      - "9000:9000"
    volumes:
      - codep_sonarqube_conf:/opt/sonarqube/conf
      - codep_sonarqube_data:/opt/sonarqube/data
      - codep_sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - codep_network
    restart: unless-stopped
  sonarqube-db:
    image: postgres:13.12
    container_name: codep_sonarqube_db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - codep_sonarqube_postgres:/var/lib/postgresql/data
    networks:
      - codep_network
    restart: unless-stopped
networks:
  codep_network:
    driver: bridge
    name: codep_network
volumes:
  codep_jenkins_data:
  codep_jenkins_docker_certs:
  codep_nexus_data:
  codep_gitlab_config:
  codep_gitlab_logs:
  codep_gitlab_data:
  codep_gitlab_postgres:
  codep_redis_data:
  codep_sonarqube_conf:
  codep_sonarqube_data:
  codep_sonarqube_extensions:
  codep_sonarqube_postgres:
